language: java
dist: trusty
before_install:
- curl -O http://central.maven.org/maven2/org/python/jython-installer/2.7.1b3/jython-installer-2.7.1b3.jar
- java -jar jython-installer-2.7.1b3.jar -s -d /tmp/jython
- "/tmp/jython/bin/jython --version"
- mkdir -p ~/.gradle
- echo jythonInterpreter=/tmp/jython/bin/jython >> ~/.gradle/gradle.properties
script: "./gradlew check"
notifications:
  slack:
    secure: Vl67/o/Z/q71mpulDpfGgHEBSD1sXYGeg4FC/0580EUny+Pzoc9Q3hfwfXSI15jretZMpf19/8BUGZLgHq7mE5gnZ1kdTM7HYVQrvF2xQ94F3ivT42wrH4kawx6ky5W/tOeFgMpDu/dCPhHrx5mIMo3qt/uizCNtPch1YaH502RIt1s6Op+4w0ZwsUFewS/AStEl1+IBLd21UJA8wF4KSsgZ4I9w0kH/IS+UjWhA2Nky70HvhahGykmO/a/4yrvBdf811flUgvNuEOmJ/SxrXxF5RKEpirlQIhkBHL9OoUoKnjn5jHUaievaynh1FbsawhTGWazeHzphfJ64DnRWy5hhpGgg/PwLGtCB33etzhkwxmRXKCzLvKJGma/djQdct54AnOE1bw9obdQ+z8NSMq2QYLyFaNatjkgMLVLFRs/AqEcI84n3Ez0f3NAvsrDP1VerOUqa8rcxWyLCVoaI2lDOUfCya+CHhW6lTuFnhYpdzi3BckERhV2+qB4FFRSoGPs5uCmAb6tH303Zo+MY1vcGmTpn64fuXTWRr/CHw56yyI3pQaRLfqQExq77E1hclmg+t5x+C0mwXX8i20MMEskQrWPF8HppOXHzG4vydLgcTdVTxZZ8qSSfgZAed0tK359pHV0JaYVXql55f7ktpMJQoSilYtPT6Rs3GmTsvhg=
deploy:
  provider: releases
  api_key:
    secure: YB1eRSLC3jXJxHrt6NoUeHu3ErKU+Y5I15DGugzuLPk16qJpIprjqxWrgNHoi2/hZSh5lpF/iES/c63cSliZf9hU8vgrdGZDEL05hmlK7KjDWZBiNtFadBuF6RJE8cnVho2iQXdj/5H6wJeSa12gnP8U/TWfMdf5ceAbJGyFaZPd49Wpa0LvHDw9Ys59tp79VpB1IO185O+2l8YPbj9udvmPf8VNT3uKexH4mbcYICUeMH5JV5K0BLSpBa+yFkv/HgDxfItx6oyMr8pjwnbjhTgS8oh/1+7sCaLMZsq9+yUKkpT9WPWUKpjkVt3LCkjFojwVM3/UcJle8zLjjK0tKX7Trh2Qy3/6Wh4SUpJO/TmPqvtVsn9ZtK7zL1uKdlQfP8sz1GpaCGbx1z7+AEaGp1pvLz1eqOFATTOJQYlvcrZtSW1yQ91++FkHux8bRaPFaQzcLYDXLt0rLtO9ks+jxrDZ9oP8SfaQ9NorjWBklMxucnTkCp69wL1PpOBQJCyLzJ1wumFUaLEv2a7H3+5prpKnjukAteFaiFePPtHxBEiF8M1HabIRzww6zun51gBmqaWIBfV+eOoGhzB+uj/1ZRJPw7eVgBRx/Ejj2XB0Z2T821Y/3gH8bnxpwEXYeJhPowUlHdGzJYt8/huCQ2rWJRqb+UxkogdYy1jo1V+Ln84=
  file: build/distributions/xld-export-policy-plugin-5.1.0.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-export-policy-plugin
