language: java
dist: trusty
before_install:
- curl -O http://central.maven.org/maven2/org/python/jython-installer/2.7.1b3/jython-installer-2.7.1b3.jar
- java -jar jython-installer-2.7.1b3.jar -s -d /tmp/jython
- /tmp/jython/bin/jython --version
- mkdir -p ~/.gradle
- echo jythonInterpreter=/tmp/jython/bin/jython >> ~/.gradle/gradle.properties
script: ./gradlew check
notifications:
  hipchat:
    rooms:
      secure: 09F60n0/qIkY4kwyDG+G94C3N9ajqJQ5ebFGmZI8S9+cuXm8VjVrhGoKJj1yDU/5Q52haYRn03vREgrlaYEOX+IgV6o++xypkFGXyfaRPjFfGKRlEsVWU0d4x4LWfzbufDfDQTlqpTTo/8s1iCB2JH/wbWoCY0aBBr7F1AWv1UiJh2qAAYKg+k85p0eFk4G+g/SoXRwcyjSz3bpznWKOMF9OPq46IiGIwIw++u8bP4lbskqeAmAjGVxTKP71ErNpt6y+2n6MyPpPTkrlXoYQslaK3uD6uF7wZbx5vGYPO3TS1R6asjY4308s1lmGS9jAbAYLaq1Wwm2ZZtSZFsgq8coM4gCeRJg8MdjVsZSx5Wc9+Gfw87zC0S+BvLfelN0BRugGRKtK2zjYy/HfqZdk21l/oxEbEjMByhRACitnH58APz8KnBnhY8jVJLxsGewKZvtz0Rs19+QWocG9Gs0qKkLu5xIXexmCWeIWNqMRgvuLHh0sqs2Adn3SpnINdvuUXVH8/AA8W7jZgWH8IOr3bvLpxAzrS9itHkNYLQhDWAmg334OOAqHDgc7tQi0GcsvSGR9yaIXuHrXZEMxfCwBG+ZkQ7HOZkyxLOMk8/lQYwgKhR8WbCrwtG0k7DUAiUFkaGjwnG98X7lAjBi1Y4erC1oVBJNcpbjYt2DPv/lvIGc=
deploy:
  provider: releases
  api_key:
    secure: YB1eRSLC3jXJxHrt6NoUeHu3ErKU+Y5I15DGugzuLPk16qJpIprjqxWrgNHoi2/hZSh5lpF/iES/c63cSliZf9hU8vgrdGZDEL05hmlK7KjDWZBiNtFadBuF6RJE8cnVho2iQXdj/5H6wJeSa12gnP8U/TWfMdf5ceAbJGyFaZPd49Wpa0LvHDw9Ys59tp79VpB1IO185O+2l8YPbj9udvmPf8VNT3uKexH4mbcYICUeMH5JV5K0BLSpBa+yFkv/HgDxfItx6oyMr8pjwnbjhTgS8oh/1+7sCaLMZsq9+yUKkpT9WPWUKpjkVt3LCkjFojwVM3/UcJle8zLjjK0tKX7Trh2Qy3/6Wh4SUpJO/TmPqvtVsn9ZtK7zL1uKdlQfP8sz1GpaCGbx1z7+AEaGp1pvLz1eqOFATTOJQYlvcrZtSW1yQ91++FkHux8bRaPFaQzcLYDXLt0rLtO9ks+jxrDZ9oP8SfaQ9NorjWBklMxucnTkCp69wL1PpOBQJCyLzJ1wumFUaLEv2a7H3+5prpKnjukAteFaiFePPtHxBEiF8M1HabIRzww6zun51gBmqaWIBfV+eOoGhzB+uj/1ZRJPw7eVgBRx/Ejj2XB0Z2T821Y/3gH8bnxpwEXYeJhPowUlHdGzJYt8/huCQ2rWJRqb+UxkogdYy1jo1V+Ln84=
  file: build/distributions/xld-export-policy-plugin-5.1.0.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-export-policy-plugin
