language: java
sudo: true
before_install:
- sudo apt-get install jython
- mkdir -p ~/.gradle
- echo jythonInterpreter=jython >> ~/.gradle/gradle.properties
script: gradle check -PjythonInterpreter=jython
